version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.20.3
    container_name: gitea
    environment:
      - USER_UID=${USER_UID} #1000
      - USER_GID=${USER_GID} #1000
      - GITEA__database__DB_TYPE=${DB_TYPE} #postgres
      - GITEA__database__HOST=${DB_HOST} #db:5432
      - GITEA__database__NAME=${DB_NAME} #gitea
      - GITEA__database__USER=${DB_USER} #gitea
      - GITEA__database__PASSWD=${DB_PASSWD} #gitea
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3310:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USER} #gitea
      - POSTGRES_PASSWORD=${DB_PASSWD} #gitea
      - POSTGRES_DB=${PG_DB} #gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
   
  runner:
    image: gitea/act_runner:nightly
    container_name: runner
    restart: unless-stopped
    environment:
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
    depends_on:
      - server

